name: Create, Test, and Destroy GKE Cluster

on:
  workflow_dispatch:

jobs:
  create-test-destroy:
    name: Create, Test, and Destroy GKE Cluster
    runs-on: ubuntu-latest #[self-hosted, gke-runners]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'
          export_default_credentials: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./GHA-S-2/terraform
        run: |
          pwd
          ls -ltr 
          terraform init
          pwd

      - name: Debug Project ID and Credentials JSON
        run: |
          pwd
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Credentials JSON (first 10 chars): $(echo '${{ secrets.GCP_SA_KEY_JSON }}' | cut -c1-10)"  # Display only part of the JSON to ensure it's there

      - name: Terraform Plan
        working-directory: ./GHA-S-2/terraform
        run: |
          # Set debug logging environment variable for Terraform
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform-debug.log  # Optional: Save logs to a fi
          pwd
          ls -ltr
          terraform plan '-var="project_id=${{ secrets.GCP_PROJECT_ID }}"' '-var="credentials_file=${{ secrets.GCP_SA_KEY_JSON }}"' '-out=tfplan'
          pwd

      - name: Terraform Apply - Create GKE Autopilot Cluster
        working-directory: ./GHA-S-2/terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="credentials_json=${{ secrets.GCP_SA_KEY_JSON }}"

      - name: Extract Terraform Outputs
        id: tf_outputs
        working-directory: GHA-S-2/terraform
        run: |
          echo "GKE_CLUSTER_NAME=$(terraform output -raw gke_cluster_name)" >> $GITHUB_ENV
          echo "GKE_CLUSTER_REGION=$(terraform output -raw gke_cluster_region)" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=$(terraform output -raw project_id)" >> $GITHUB_ENV

      - name: Configure kubectl context
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME \
            --region $GKE_CLUSTER_REGION \
            --project $GCP_PROJECT_ID

      - name: Verify Cluster - Get Pods
        run: |
          kubectl get pods --namespace=default

      - name: Terraform Destroy - Cleanup GKE Cluster
        if: always()  # important: destroy even if kubectl step fails
        working-directory: GHA-S-2/terraform
        run: |
          terraform destroy -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="credentials_json='${{ secrets.GCP_SA_KEY_JSON }}'"
